language: node_js
sudo: false
node_js:
  - "6.0"
  - "8.0"
before_install:
  - sudo apt-get install libasound2-dev alsa-utils alsa-oss
cache:
  directories:
    - node_modules
script:
  - npm run travis
